### ISSUE TITLE
getting "EOF" error when running 

### ISSUE THREAD

**Issue by DotMatrixNate** [samuelyuan/Civ5MapImage#1]
I'm getting an "EOF" error whenever I try to run this, both on Window and Linux
![errorIget](https://user-images.githubusercontent.com/107432158/212235049-d0b1d61b-87d1-4153-8316-a002e5a32d94.png)

**Comment by samuelyuan** [comment]
Have you tested any other maps and confirmed they are able to load? If it's just this one map, it could be an issue with the map or there is a case not covered by the code.

**Comment by DotMatrixNate** [comment]
> Have you tested any other maps and confirmed they are able to load? If it's just this one map, it could be an issue with the map or there is a case not covered by the code.

I've tried it with several different maps. Aswell as 3 separate computers, and each one, to my recollection, gave me the same error.

**Comment by samuelyuan** [comment]
Can you attach a map that you tried?

**Comment by NathanDinosaur** [comment]
> Can you attach a map that you tried?
[penis.Civ5Map.zip](https://github.com/samuelyuan/Civ5MapImage/files/10447574/penis.Civ5Map.zip)

**Comment by DotMatrixNate** [comment]
> Can you attach a map that you tried?

[map.Civ5Map.zip](https://github.com/samuelyuan/Civ5MapImage/files/10447586/map.Civ5Map.zip)

I'm running Manjaro Linux and running this program with the command:
`./Civ5MapImage -input=map.Civ5Map -output=earth.png`

**Comment by samuelyuan** [comment]
The map file doesn't load for me either. The EOF error happens because the file ends after the map tiles is read, but the program assumes gameDescriptionHeader is present in the file and continues to read data beyond the end of the file.

**Comment by MarqFJA87** [comment]
Facing the same issue with this map: 
[Bismarck-Germany_OrderSpace.zip](https://github.com/user-attachments/files/17186860/Bismarck-Germany_OrderSpace.zip)

Is it similarly hopeless?

**Comment by samuelyuan** [comment]
Updated code to handle maps without game description header. I tested both of the inputs in this issue and was able to generate an image for each.
![output](https://github.com/user-attachments/assets/dcaf3a1b-d425-4cd5-b65b-8b6b70065940)
![output](https://github.com/user-attachments/assets/b267d986-8092-447c-939b-d6ffa282c991)
